[package]
name = "fast_1brc"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam = "0.8.4"
fxhash = "0.2.1"
jemallocator = "0.5.4"
memchr = "2.7.4"
num_cpus = "1.16.0"

[features]
default = []
simd = []
